import { configureStore, createSlice } from "@reduxjs/toolkit";

// Create a slice
const counterSlice = createSlice({
  name: "counter",
  initialState: {
    isAuthenticated: false,
    useDetails: [],
  },
  reducers: {
    loginUser: (state, action) => {
      console.log(action);
      return {
        ...state,
        isAuthenticated: true,
        useDetails: action?.payload,
      };
    },
    userCategory: (state, action) => {
      return {
        ...state,
        category: action?.payload,
      };
    },
    category: (state, action) => {
      return {
        ...state,
        category: action?.payload,
      };
    },
  },
});

// Export the actions generated by createSlice
export const { loginUser } = counterSlice.actions;

// Create the Redux store
const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
  },
});

export default store;
